### ISSUE TITLE
Suggest fails with weird unicode characters

### ISSUE THREAD

**Issue by javiber** [MSeal/cython_hunspell#17]
The library fails to process some unicode characters:

```
>>> from hunspell import Hunspell
>>> h = Hunspell()
>>> h.suggest("Ω")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hunspell/hunspell.pyx", line 223, in hunspell.hunspell.HunspellWrap.suggest
    return self.action('suggest', word)
  File "hunspell/hunspell.pyx", line 246, in hunspell.hunspell.HunspellWrap.action
    copy_to_c_string(word, &c_word, self._dic_encoding)
  File "hunspell/hunspell.pyx", line 41, in hunspell.hunspell.copy_to_c_string
    return byte_to_c_string(<bytes>py_string.encode(encoding, 'strict'), holder, encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03a9' in position 0: ordinal not in range(256)
>>> h._system_encoding
'UTF-8'
>>> h._dic_encoding
'ISO8859-1'
>>> 
```

The problem seems to be the `_dic_encoding`

**Comment by MSeal** [comment]
So there's some complexity here, the hunspell library you're using is encoded in latin-1. But latin-1 doesn't have greek character sets available (https://cs.stanford.edu/people/miles/iso8859.html) so when it tries to map the Omega character it can't. The library opts to raise an exception instead of silently failing to match the character to anything known. We could make the library always return no matches for suggest on unknown characters, but that does risk leaving a confusing failure pattern for those unawares.

If you wanted to make the suggestion safer with a risk of not matching, you could do:

```
In [19]: "Ω".encode(h._dic_encoding, 'replace').decode()                                                                                    
Out[19]: '?'

In [20]: h.suggest("Ω".encode(h._dic_encoding, 'replace').decode())                                                                         
Out[20]: ('e', 's', 'i', 'a', 'n', 'r', 't', 'o', 'l', 'c', 'd', 'u', 'g', 'm', 'p')
```

We could make an option to actions like suggest to not be always 'strict', and take conversion options as an argument. I'd be open to a PR for that change.

if you want to fix this more completely in your setup, the encoding is set by the library `.aff` file for the dictionary. You can see that there is a 'test.aff' file the library uses for testing which is in UTF-8 encoding as an example:

```
In [13]: h = Hunspell('test')                                                                                                               

In [14]: h._dic_encoding                                                                                                                    
Out[14]: 'UTF-8'

In [15]: h.suggest("Ω")                                                                                                                     
Out[15]: ('E', 'S', 'I', 'A', 'N', 'R', 'T', 'O', 'L', 'C', 'D', 'U', 'G', 'M', 'P')
```

but in order for a dictionary to use that encoding you need to rewrite the `*.dic` file to have the desired encoding.

Yet another option would be for us to support a `change_dic_encoding` method which copies the entire dictionary from one encoding to another.

**Comment by javiber** [comment]
Gotcha, Do you think it makes sense to convert the dictionaries provided in this library to UTF-8 or should I load a custom one on my other project?

**Comment by MSeal** [comment]
I'd make a custom one -- those dictionaries are a copy of the hunspell library's provided dictionaries. I'll think of ways to make such customization options available in the library itself down the road.

**Comment by javiber** [comment]
Alright! thanks for the response, I'll close the issue now.
