### ISSUE TITLE
How to get suggestions for entire sentence ?

### ISSUE THREAD

**Issue by astariul** [MSeal/cython_hunspell#39]
With the `hunspell` command line, we can get suggestions for entire sentences : 

`echo "i loove this package" | hunspell -d en-US `

output : 

> Hunspell 1.7.0
> *
> & loove 2 2: love, loose
> *
> *

---

How can I achieve the same from python ?

**Comment by MSeal** [comment]
You can use the `bulk_suggest` and pass the words in as a list:

```
h.bulk_suggest("i loove this package".split())
```

This will give you back a dictionary of the word -> [suggestions] list in order of best fit. You can then choose to use those results to replace outputs.

Otherwise you can iterate through each word via split and call suggest on each one to get that particular word's evaluation.

**Comment by astariul** [comment]
@MSeal Thanks for your answer !

But I think Hunspell also do split on other characters than space. For example : 

`echo "I loove:this package" | hunspell -d en-US`

will print : 

> *
> & loove 2 2: love, loose
> *
> *

But if we split only on space, `loove` and `this` are not separated. But not every punctuation does that (for example `'` is not used as a separator).

I was wondering if there is a fixed list of punctuation used as separators or if this list change depending on the languages.

**Comment by MSeal** [comment]
Choosing separators to split words would be up to you as the caller. Here's a few examples of options available: https://towardsdatascience.com/5-simple-ways-to-tokenize-text-in-python-92c6804edfc4
