### ISSUE TITLE
Error during compilation with PyInstaller

### ISSUE THREAD

**Issue by prabhatM** [MSeal/cython_hunspell#9]
During building EXE for Windows with PyInstaller, there's an error showing up. hunspell.platform() not found.

Prabhat

**Comment by prabhatM** [comment]
Hi,
Kindly help with Pyinstaller setup. The issue is persistent.

Regards

Prabhat

**Comment by MSeal** [comment]
Sorry, I've been quite busy and haven't had any bandwidth to look at this project atm. I can try taking a look this weekend. If it's pretty clear what's needed a PR is always appreciated as well :)

**Comment by prabhatM** [comment]
Thank you so much for this response. Can't tell you how much I appreciate
it. It's like an oasis in a big desert! :)

I am trying to do a small dictionary application using CyHunspell and Kivy
for the user interface. It's working like a charm. However, when I tried to
compile the application to a single EXE, it's failing showing the error
message "hunspell.platform() not found. I am using Pip 18.1, Python 3.6,
Pyinsyaller 3.5 on Windows 7.

Also would to like bring to your notice that CyHunspell is not installing
on Windows 10 with Pip 18.1 .

Thank you for giving us the Cython version of Hunspell. A little attention
will help this great project alive.

Thank you again for your time.

Regards

Prabhat

**Comment by MSeal** [comment]
So I looked into the PyInstaller issue. This is going to be a pain to make work given the package search tooling in pyinstaller isn't equipped to track down the package dependencies from cython modules well. In particular you'd need to follow https://pythonhosted.org/PyInstaller/spec-files.html?highlight=binary and pull over the binary dependencies via this pattern: https://stackoverflow.com/questions/24525861/building-cython-compiled-python-code-with-pyinstaller. You'd also need to fetch the binaries for hunspell (which the cyhunspell installer fetches if they're missing) and include those compiled binaries.

Given the scope of digging it'd take to make this work I haven't gone through all the steps to produce a working exe with this pattern. I've however left the relevant links for you if you want to explore the option and I'm glad to help point out how to find particular library dependencies if you get an error about loading them at runtime in going through this process.

One thing to note, is at the end of this the binaries will only run on particular installations of windows. They may fail to run on other versions of windows, which is why the setuptools for the library here try to compile against an array of platform targets on demand. Though I imagine any windows 10 machine should be fine with an exe build from another windows 10 machine.

**Comment by prabhatM** [comment]
Considering my limited technical abilities, this looks out of my comfort
zone.

However, after some searching, I came across this link.

https://github.com/prologic/pyinstaller-cython-bundling/blob/master/README.md


Will it help you resolve the issue?

Regards

Prabhat MOHANTY

**Comment by MSeal** [comment]
It's the first step yes. You'd need to modify it further, combining the cyhunspell code/ibs with the hunspell libs and making a non-bash specific builder perhaps. May still be outside your comfort zone and would likely still be a bit fragile.

**Comment by MSeal** [comment]
This should be resolved with the new 2.0.0 release
